package com.mycompany.traceabilityproyect;
// Generated 15/09/2015 01:03:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Datasource generated by hbm2java
 */
public class Datasource  implements java.io.Serializable {


     private Integer id;
     private Metadato metadato;
     private String usuario;
     private String pass;
     private String host;
     private String puerto;
     private int nombreBd;
     private int motorBd;
     private Set pasos = new HashSet(0);

    public Datasource() {
    }

	
    public Datasource(Metadato metadato, String usuario, String pass, String host, String puerto, int nombreBd, int motorBd) {
        this.metadato = metadato;
        this.usuario = usuario;
        this.pass = pass;
        this.host = host;
        this.puerto = puerto;
        this.nombreBd = nombreBd;
        this.motorBd = motorBd;
    }
    public Datasource(Metadato metadato, String usuario, String pass, String host, String puerto, int nombreBd, int motorBd, Set pasos) {
       this.metadato = metadato;
       this.usuario = usuario;
       this.pass = pass;
       this.host = host;
       this.puerto = puerto;
       this.nombreBd = nombreBd;
       this.motorBd = motorBd;
       this.pasos = pasos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Metadato getMetadato() {
        return this.metadato;
    }
    
    public void setMetadato(Metadato metadato) {
        this.metadato = metadato;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }
    public String getPuerto() {
        return this.puerto;
    }
    
    public void setPuerto(String puerto) {
        this.puerto = puerto;
    }
    public int getNombreBd() {
        return this.nombreBd;
    }
    
    public void setNombreBd(int nombreBd) {
        this.nombreBd = nombreBd;
    }
    public int getMotorBd() {
        return this.motorBd;
    }
    
    public void setMotorBd(int motorBd) {
        this.motorBd = motorBd;
    }
    public Set getPasos() {
        return this.pasos;
    }
    
    public void setPasos(Set pasos) {
        this.pasos = pasos;
    }




}


