package com.mycompany.traceabilityproyect;
// Generated 15/09/2015 05:38:39 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Datasource generated by hbm2java
 */
public class Datasource  implements java.io.Serializable {


     private BigDecimal id;
     private Paso paso;
     private String usuario;
     private String password;
     private String host;
     private BigDecimal puerto;
     private String nombreBd;
     private String motorBd;
     private Set metadatos = new HashSet(0);

    public Datasource() {
    }

	
    public Datasource(BigDecimal id, Paso paso, String usuario, String password, String host, BigDecimal puerto, String nombreBd, String motorBd) {
        this.id = id;
        this.paso = paso;
        this.usuario = usuario;
        this.password = password;
        this.host = host;
        this.puerto = puerto;
        this.nombreBd = nombreBd;
        this.motorBd = motorBd;
    }
    public Datasource(BigDecimal id, Paso paso, String usuario, String password, String host, BigDecimal puerto, String nombreBd, String motorBd, Set metadatos) {
       this.id = id;
       this.paso = paso;
       this.usuario = usuario;
       this.password = password;
       this.host = host;
       this.puerto = puerto;
       this.nombreBd = nombreBd;
       this.motorBd = motorBd;
       this.metadatos = metadatos;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Paso getPaso() {
        return this.paso;
    }
    
    public void setPaso(Paso paso) {
        this.paso = paso;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }
    public BigDecimal getPuerto() {
        return this.puerto;
    }
    
    public void setPuerto(BigDecimal puerto) {
        this.puerto = puerto;
    }
    public String getNombreBd() {
        return this.nombreBd;
    }
    
    public void setNombreBd(String nombreBd) {
        this.nombreBd = nombreBd;
    }
    public String getMotorBd() {
        return this.motorBd;
    }
    
    public void setMotorBd(String motorBd) {
        this.motorBd = motorBd;
    }
    public Set getMetadatos() {
        return this.metadatos;
    }
    
    public void setMetadatos(Set metadatos) {
        this.metadatos = metadatos;
    }




}


