package com.mycompany.traceabilityproyect;
// Generated 15/09/2015 01:03:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Metadato generated by hbm2java
 */
public class Metadato  implements java.io.Serializable {


     private Integer id;
     private String tabla;
     private String campo;
     private int referencia;
     private Set datasources = new HashSet(0);

    public Metadato() {
    }

	
    public Metadato(String tabla, String campo, int referencia) {
        this.tabla = tabla;
        this.campo = campo;
        this.referencia = referencia;
    }
    public Metadato(String tabla, String campo, int referencia, Set datasources) {
       this.tabla = tabla;
       this.campo = campo;
       this.referencia = referencia;
       this.datasources = datasources;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTabla() {
        return this.tabla;
    }
    
    public void setTabla(String tabla) {
        this.tabla = tabla;
    }
    public String getCampo() {
        return this.campo;
    }
    
    public void setCampo(String campo) {
        this.campo = campo;
    }
    public int getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(int referencia) {
        this.referencia = referencia;
    }
    public Set getDatasources() {
        return this.datasources;
    }
    
    public void setDatasources(Set datasources) {
        this.datasources = datasources;
    }




}


