package com.mycompany.traceabilityproyect;
// Generated 15/09/2015 01:03:49 PM by Hibernate Tools 4.3.1



/**
 * Paso generated by hbm2java
 */
public class Paso  implements java.io.Serializable {


     private Integer id;
     private Datasource datasource;
     private String nombre;
     private String tipo;

    public Paso() {
    }

    public Paso(Datasource datasource, String nombre, String tipo) {
       this.datasource = datasource;
       this.nombre = nombre;
       this.tipo = tipo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Datasource getDatasource() {
        return this.datasource;
    }
    
    public void setDatasource(Datasource datasource) {
        this.datasource = datasource;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


