package com.mycompany.traceabilityproyect;
// Generated 15/09/2015 05:38:39 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PasoActividad generated by hbm2java
 */
public class PasoActividad  implements java.io.Serializable {


     private BigDecimal id;
     private Flujo flujo;
     private Paso paso;
     private String actividad;
     private BigDecimal secuencia;
     private String entrada;
     private String salida;

    public PasoActividad() {
    }

	
    public PasoActividad(BigDecimal id, Flujo flujo, Paso paso, String actividad, String entrada, String salida) {
        this.id = id;
        this.flujo = flujo;
        this.paso = paso;
        this.actividad = actividad;
        this.entrada = entrada;
        this.salida = salida;
    }
    public PasoActividad(BigDecimal id, Flujo flujo, Paso paso, String actividad, BigDecimal secuencia, String entrada, String salida) {
       this.id = id;
       this.flujo = flujo;
       this.paso = paso;
       this.actividad = actividad;
       this.secuencia = secuencia;
       this.entrada = entrada;
       this.salida = salida;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Flujo getFlujo() {
        return this.flujo;
    }
    
    public void setFlujo(Flujo flujo) {
        this.flujo = flujo;
    }
    public Paso getPaso() {
        return this.paso;
    }
    
    public void setPaso(Paso paso) {
        this.paso = paso;
    }
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }
    public BigDecimal getSecuencia() {
        return this.secuencia;
    }
    
    public void setSecuencia(BigDecimal secuencia) {
        this.secuencia = secuencia;
    }
    public String getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(String entrada) {
        this.entrada = entrada;
    }
    public String getSalida() {
        return this.salida;
    }
    
    public void setSalida(String salida) {
        this.salida = salida;
    }




}


