package com.mycompany.traceabilityproyect;
// Generated 15/09/2015 05:38:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paso generated by hbm2java
 */
public class Paso  implements java.io.Serializable {


     private String id;
     private String nombre;
     private String tipo;
     private Set datasources = new HashSet(0);
     private Set pasoActividads = new HashSet(0);

    public Paso() {
    }

	
    public Paso(String id, String nombre, String tipo) {
        this.id = id;
        this.nombre = nombre;
        this.tipo = tipo;
    }
    public Paso(String id, String nombre, String tipo, Set datasources, Set pasoActividads) {
       this.id = id;
       this.nombre = nombre;
       this.tipo = tipo;
       this.datasources = datasources;
       this.pasoActividads = pasoActividads;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getDatasources() {
        return this.datasources;
    }
    
    public void setDatasources(Set datasources) {
        this.datasources = datasources;
    }
    public Set getPasoActividads() {
        return this.pasoActividads;
    }
    
    public void setPasoActividads(Set pasoActividads) {
        this.pasoActividads = pasoActividads;
    }




}


